### ISSUE TITLE
Split of MPF dataset

### ISSUE THREAD

**Issue by KruskalLin** [materialsvirtuallab/matgl#109]
Hi,

Thanks for your great work! I see you are using seed 42 to split the MPF 2021 dataset. May I ask if this is the same split used in the paper [1]? I didn't find out the information in the paper [1], so just ask in case. 

Thank you and looking forward to your reply!

Best Regards

[1] Chen, Chi, and Shyue Ping Ong. "A universal graph deep learning interatomic potential for the periodic table." Nature Computational Science 2.11 (2022): 718-728.

**Comment by shyuep** [comment]
MatGL is a re-implementation. The paper used the TF version. I wouldn't assume that even if the random seems are the same that it would lead to the same answers. But generally, the results shouldn't depend too much on the seed used.
