### ISSUE TITLE
Placeholder variable for state features in MEGNet for crystals

### ISSUE THREAD

**Issue by gprashant17** [materialsvirtuallab/matgl#122]
Hi, I am using the MEGNet model for band gap prediction from crystal structures ([MEGNet-MP-2019.4.1-BandGap-mfi](https://github.com/materialsvirtuallab/matgl/tree/main/pretrained_models/MEGNet-MP-2019.4.1-BandGap-mfi)), and I am trying to understand the purpose of using two zeros as a placeholder for the global state feature and the way it is processed. Running the following command 

`mgl predict -m MEGNet-MP-2019.4.1-BandGap-mfi --infile crys.cif`

with default arguments, I get an error in line https://github.com/materialsvirtuallab/matgl/blob/4961e1c1dee83031e6d4490d2778016f83ebedd6/matgl/layers/_graph_convolution.py#L62 

`File "/network/scratch/p/prashant.govindarajan/crystal_design_project/crystal-design/crystal_design/matgl/matgl/layers/_graph_convolution.py", line 62, in _edge_udf
    inputs = torch.hstack([vi, vj, eij, u])
RuntimeError: Tensors must have same number of dimensions: got 2 and 3`

The state feature of size `[2,]` passes through the embedding layer to get an output of shape `[2,16]`. Because of this, the state feature becomes 3 dimensions once broadcasted across nodes in the graph. This causes dimension mismatch error while concatenating features in the edge update function in the graph convolution layer. So does the placeholder zero tensor that represents the state feature need to pass through the embedding layer i.e., this line?
https://github.com/materialsvirtuallab/matgl/blob/4961e1c1dee83031e6d4490d2778016f83ebedd6/matgl/layers/_embedding.py#L78
If yes, then how to resolve the dimension error in this case? Thank you in advance!

**Comment by shyuep** [comment]
@kenko911 Pls reply and investigate.

**Comment by kenko911** [comment]
Hi @gprashant17. Sorry for the late reply. We just extended the functionality of mgl command to enable the prediction of multi-fidelity MEGNet model for bandgap prediction. Please get the latest version of matgl and take reference from the unit test in tests/test_cli.py to perform bandgap prediction. For the concept, I would refer the original work  Chen, C.; Zuo, Y.; Ye, W.; Li, X.; Ong, S. P. Learning Properties of Ordered and Disordered Materials from Multi-Fidelity Data. Nature Computational Science, 2021, 1, 46–53. DOI: [10.1038/s43588-020-00002-x](https://nature.com/articles/s43588-020-00002-x). This paper provide very detailed descriptions for state features. Thanks!!

**Comment by gprashant17** [comment]
Thanks for the reply. It worked. I just a quick follow-up question -- is there an equivalent command that takes multiple cif files, creates a batch, and predicts band gap for all crystals in the batch?
