### ISSUE TITLE
Bad coding in M3GNetDataset.load

### ISSUE THREAD

**Issue by shyuep** [materialsvirtuallab/matgl#124]
https://github.com/materialsvirtuallab/matgl/blob/000ff489cffff957ed09a8207286c2fc7993d429/matgl/graph/data.py#L328C11-L328C11

I am puzzled why this code assumes there is a `labels.json` file somewhere, when the other three files have explicit file names given. And in the preceding save method, the labels.json is written using a `file.write` method. This is not how proper json is written. JSON is written using the `json.dump` method to ensure that it is proper json format.

Also, there is no unittest for the labels.json loading.

**Comment by kenko911** [comment]
You are right, I am thinking to use pickle instead of json. What do you think?

**Comment by shyuep** [comment]
Json is file. It is more readable. I hate pickle. Whether pickle or json, file.write is not the way to write it.
