### ISSUE TITLE
Should bond vector + distance calculations be carried out in converters?

### ISSUE THREAD

**Issue by lbluque** [materialsvirtuallab/matgl#129]
I see the following code repeated almost verbatim everywhere that an atomic graph is used:

```python
graph, state_attr = converter.get_graph(structure)
bond_vec, bond_dist = compute_pair_vector_and_distance(graph)
graph.edata["bond_vec"] = bond_vec
graph.edata["bond_dist"] = bond_dist
```

Would it make sense to have those computed in the converter itself? Since almost all use cases of an atomic graph will want those edge attributes.

**Comment by shyuep** [comment]
Agree.

**Comment by shyuep** [comment]
Lemme quickly just fix this.

**Comment by shyuep** [comment]
Well, turns out it is not an easy fix. The logic is easy enough. But once I move the bond vec and dist into the get_graph method, it results in a RuntimeError: One of the differentiated Tensors does not require grad error.

**Comment by lbluque** [comment]
Ah thanks for investigating! 

I'll see if I can find a workaround myself, if not then we can leave as is.

**Comment by lbluque** [comment]
Yes, confirmed what you mention.

`compute_pair_vector_and_distance` must happen in `forward` otherwise the computational graph is not recorded properly for grads wrt to "pos" and "bond_vec".

During my investigation I cleanup up the code a little bit in #130

**Comment by kenko911** [comment]
Hi @lbluque, thanks for coming up with the issue. I think we need to keep his function in forward so that we can calculate forces and other derivatives

**Comment by lbluque** [comment]
> Hi @lbluque, thanks for coming up with the issue. I think we need to keep this function in forward so that we can calculate forces and other derivatives

Thanks @kenko911, I understand. This issue can be closed.

**Comment by shyuep** [comment]
Just a final comment that I was toying with writing a derived class called MatGraph that is a subclass of dglGraph. But apparently saving and loading are impossible

**Comment by kenko911** [comment]
Yup. I am actually reformulating both MEGNet and  M3GNetDatset such that you can easily load all dgl graphs and properties from files. I almost finished the implementations and testing is on going. Will upload it soon ;).
