### ISSUE TITLE
Supporting TorchScript?

### ISSUE THREAD

**Issue by rick433** [materialsvirtuallab/matgl#142]
Hi,

thank you for the great work. Do you plan to provide TorchScript support in the future? 

Best regards!

**Comment by shyuep** [comment]
I think it is safe to say this is something we are not exploring unless we have a pressing reason to do so. But others are welcome to add this and submit a PR.

**Comment by lbluque** [comment]
Just want to note that the bigger impediment is DGL supporting it. My understanding is it currently does not, so any effort would need to start there.
