### ISSUE TITLE
M3GNet Training Tutorial Not Working

### ISSUE THREAD

**Issue by rydeveraumn** [materialsvirtuallab/matgl#143]
Hello,

I am working through the tutorial to train a `M3GNet` model (https://matgl.ai/tutorials%2FTraining%20a%20M3GNet%20Potential%20with%20PyTorch%20Lightning.html) and it appears that the interface for `M3GNetDataset` no longer takes inputs `energies, forces, stresses`.

<img width="911" alt="image" src="https://github.com/materialsvirtuallab/matgl/assets/114163523/ef7304e2-bb6f-4e22-a9c0-d67850775297">

My `matgl` version is `0.8.3`. Could I be advised on how to proceed? Thank you in advance.

**Comment by rydeveraumn** [comment]
For anyone looking to work through the tutorial, it looks like labels are now passes as a dictionary to the `M3GNetDataset`:

<img width="707" alt="image" src="https://github.com/materialsvirtuallab/matgl/assets/114163523/471e9741-d0b0-4c45-83f2-8873fe9e80ab">

I would be happy to update the tutorial and contribute.

**Comment by shyuep** [comment]
Thanks yes. I recently refactored the Dataset class to make it more consistent and intuitive. If you can help make the adjustments to the tutorial, that would be great.

**Comment by kenko911** [comment]
I think @lbluque has pushed the fix to the tutorial for M3GNet training. I will close this issue if no any further problems.
