### ISSUE TITLE
Setting datatypes consistently

### ISSUE THREAD

**Issue by lbluque** [materialsvirtuallab/matgl#144]
I don't see a consistent choice of primitive datatypes. My guess is the default choice is intended to be `torch.float32` and `torch.int32`. But different datatypes appear throughout the code, and in particular having some tensors be float64 leads to graph data taking an unwieldy amount of storage space.

For example, when working atom graphs I find the following datatypes in their edge data:
```
bond_vec torch.float32
lattice torch.float64
pbc_offshift torch.float64
bond_dist torch.float32
pbc_offset torch.float64
```

And node data:
```
volume torch.float32
pos torch.float64
node_type torch.int64
```

I think primitive datatypes should be kept consistent.

Additionally, I was wondering if there are plans to implement a way to easily allow a global configuration of datatypes (similar to the config file in the original m3gent code)?

**Comment by shyuep** [comment]
I agree. Let's use 32 consistently. If we want, we can specify in config. But I don't see a reason since torch already defines these.

**Comment by shyuep** [comment]
Also, I can't see a situation where precision is going to be the issue for our kind of ML.

**Comment by kenko911** [comment]
Hi @lbluque and @SP, thanks for reporting issues and I fully agree that we should have a consistent dtype for floating point number and integer. As far as I know,  we can use the torch.set_default_dtype(torch.float32) for floating point numbers but 
 I not sure we have default dtype for integers.... Any suggestions?

**Comment by kenko911** [comment]
Since the default integer type is int64. Either we set default dtype of floating point numbers to 64 to make it consistent or we  every time create a integer tensor and we need to convert it to int32.

**Comment by shyuep** [comment]
I don't think the default int type is int64. torch.int is the same as torch.int32. Are there situations where we think int64 is even necessary? I can't imagine so.....

**Comment by kenko911** [comment]
My torch version is 2.0.1 and I just simple tested with torch.tensor([1]).dtype and output torch.int64.....

**Comment by lbluque** [comment]
I think one thing to note is that when creating a tensor from a numpy array I think the dtype is inferred from the array. So for example in the graph converter those may need to be specified explicitly.

**Comment by shyuep** [comment]
I pushed a few minor changes to convert float64->float32. One thing is that I noticed the compute_threebody is rather strangely coded. It puts g.num_nodes(), which is an int, in a list and try to loop that one item list. It is nuts. I also noticed that the function uses numpy. In my view, all matgl should simply use torch.func where possible. As far as I know, torch already has almost feature parity with numpy in this regard. There is no good reason to convert tensors to numpy arrays and then have to move it back to tensors again. @kenko911 Pls look for all areas where numpy can be removed.

**Comment by lbluque** [comment]
Thanks for the quick update @shyuep 

Though, I actually found a structure in MP (in the calcs of `mp-695213`) where forcing the `pbc_offshift` edge data  to float32, changes the resulting line graph with 3A cutoff bc two of the bond distances are just at that cutoff.

This should be a very strange edge case, but if we want to address it one could simply add a distance tolerance to the three-body cutoff.

**Comment by shyuep** [comment]
Closing this since the new pushes seem to fix all this. Thanks for all the great discussion.
