### ISSUE TITLE
[Feature Request]: allow distinguishing atoms of the same symbol

### ISSUE THREAD

**Issue by matthewcarbone** [materialsvirtuallab/matgl#166]
### Problem

Suppose we have a situation where we want to predict an _atom-specific_ property. For example, the spectrum of a single absorbing site on a material. It would be nice to be able to label that atom as distinct.

For example, given material with symmetrically unique elements `Ti, Ti, O, O, O, O`, perhaps we would like to distinguish the first `Ti` as "absorber" or "special" in some way. Thus it does not get the standard Ti label, it gets index `len(element_types) + 1` or something like this.

### Proposed Solution

In #164, I've allowed for an extra index as a "catch all" for atoms not specified in the `elements_list`. I'd like to add an option for yet another index, a "special" atom. In other words, the following two materials would produce the same atom label featurization:

- `Ti, Ti, O, O, O, O` with atom index 0 indicated as "special"
- `Mg, Ti, O, O, O, O` with the standard use of the code

I'm happy to do the coding on this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shyuep** [comment]
I guess a quick question is can't all these be achieved by pre-processing the structures beforehand? E.g., Simply change all first indices to some unused element? We can also potentially support the special Pymatgen DummySpecies X. That should address all these issues.

**Comment by matthewcarbone** [comment]
> We can also potentially support the special Pymatgen DummySpecies X. That should address all these issues.

This is exactly what I mean, basically. Is there any easy way to add this into the featurization scheme? It's also reasonable to just change the structure itself beforehand. As long as "X" is supported.
