### ISSUE TITLE
[Bug]: Release workflow broken

### ISSUE THREAD

**Issue by janosh** [materialsvirtuallab/matgl#191]
### Version

v0.8.6

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [ ] Linux

### What happened?

This doesn't look right. Skips the release step even when it shouldn't. You probably wan't `if: github.event_name == 'release' && needs.tests.result == 'success'`.

https://github.com/materialsvirtuallab/matgl/blob/d9f266523983fdea0baeacc16dece83f447e5a14/.github/workflows/testing.yml#L51

Hence https://github.com/materialsvirtuallab/matgl/releases/tag/v0.8.6 didn't make it to PyPI.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shyuep** [comment]
I am unclear of the bug. This runs the release porition only when the event is release and needs: test already specifies that it should run only when the tests pass. What is the bug?

**Comment by janosh** [comment]
`github.event.name` doesn't exist. It's `github.event_name`.
