### ISSUE TITLE
[Bug]: Urgent! ValueError: Bad serialized model or bad model name

### ISSUE THREAD

**Issue by janosh** [materialsvirtuallab/matgl#193]
### Version

0.8.5

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [ ] Linux

### What happened?

`matgl` is holding up the whole MP stack with this error

> ValueError: Bad serialized model or bad model name. It is possible that you have an older model cached. Please clear your cache by running `python -c "import matgl; matgl.clear_cache()"`

```
/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/matgl/utils/io.py:213:
```

It's affecting `pymatgen`, `atomate2`, `matcalc`, `emmet`, ...
Please add tests for whatever broke so this doesn't happen again!

- https://github.com/materialsproject/pymatgen/pull/3477
- https://github.com/materialsproject/atomate2/pull/614
- https://github.com/materialsproject/atomate2/pull/615
- https://github.com/materialsvirtuallab/matcalc/pull/11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shyuep** [comment]
Erm, I think the error message says it all? @kenko911 You need to change the model number when you make internal changes like the stress computation. Otherwise the loading of the models can be wrong.

**Comment by janosh** [comment]
How come there's no test that caught this?

**Comment by ucarh** [comment]
I had this error with python 3.12, downgrading it to 3.9 solved the issue.

**Comment by shyuep** [comment]
DGL (the underlying dependency) is not even available on py3.12. In general, we would recommend using Py3.10 (or at most one version below the latest Python, which usually has bugs as well as a lot of unsupported dependencies).
