### ISSUE TITLE
[Feature Request]: Relaxation under pressure

### ISSUE THREAD

**Issue by Youjin1985** [materialsvirtuallab/matgl#201]
### Problem

Dear developers,
Considering Molecular Dynamics with Matgl supports pressure, is it possible to add external pressure to Relaxer? It would be of great benefit for studying systems in pressure ranges.

### Proposed Solution

add an option to relaxer for external pressure

### Alternatives

VASP supports setting PSTRESS in INCAR

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shyuep** [comment]
This has been implemented in the latest commit above. You can pass params to the ExpCellFilter to do constant pressure.
