### ISSUE TITLE
[Bug]: Not all data is on the same device

### ISSUE THREAD

**Issue by rydeveraumn** [materialsvirtuallab/matgl#213]
### Email (Optional)

dever120@umn.edu

### Version

0.9.1

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [X] Linux

### What happened?

1. I am attempting to run the M3GNet code on GPU
2. When I get to the `trainer.fit()` I get an error that not all data is on the same device.
3. When I `debug` this line seems to be where the code is throwing the error https://github.com/materialsvirtuallab/matgl/blob/6759ffbe3d5415bc024ab6569b6a80f05001b2ba/src/matgl/apps/pes.py#L88

Wondering if this is happening for anyone else or maybe something is off with my setup.

### Code snippet

```python
The code I am running is from this tutorial: https://matgl.ai/tutorials%2FTraining%20a%20M3GNet%20Potential%20with%20PyTorch%20Lightning.html
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kenko911** [comment]
Hi @rydeveraumn, please use torch.set_default_device('cuda') at the very beginning of your training script and set num_workers =0, generator=torch.Generator(device="cuda") combined with other args in MGLDataLoader class. It should work and please let me know if any problems.
