### ISSUE TITLE
How to use the potential of a finetuned model.

### ISSUE THREAD

**Issue by vzguille** [materialsvirtuallab/matgl#217]
I have a function which compares the M3GNet ase calculator to DFT to validate the energy, forces and stresses values. Comparing the pretrained "M3GNet-MP-2021.2.8-PES" is not a problem neither comparing a model trained solely on our generated system-specific training data. But when finetuning "M3GNet-MP-2021.2.8-PES" I can't seem to obtain coherent values from the ase calculator. From another post I see it is a problem of scaling and that I need to redefine the Potential before creating the calculator but I don't see how to proceed with this... do i need to provide the mean and std for all energies, forces and stresses, or only energies?

Pretrained model validation dataset:
m3gnet_nnp = matgl.load_model("M3GNet-MP-2021.2.8-PES")
calc_matgl = M3GNetCalculator_matgl(m3gnet_nnp)
![image](https://github.com/materialsvirtuallab/matgl/assets/82835375/94a82924-ebda-428b-b1c9-ebf6e83ef300)

After fine-tunning vaidation dataset (when  val_Total_Loss=0.414):
calc_matgl = M3GNetCalculator_matgl(lit_module_finetune.model) #(lit_module_finetune is as in the tutorial)
![image](https://github.com/materialsvirtuallab/matgl/assets/82835375/a7daf333-bb7a-4fe2-8671-1334a2c10851)

I obtain these values by using the ase calculator function swritten here:
structure_ase.calc = calc_matgl
structure_ase.get_potential_energy()
structure_ase.get_forces()
structure_ase.get_stress()

Thanks for your time

**Comment by kenko911** [comment]
Hi @vzguille, could you please share us the whole training script for further investigations?
