### ISSUE TITLE
[Feature Request]:  Implementation of other thermostats for molecular dynamics using matgl 

### ISSUE THREAD

**Issue by goodwilling** [materialsvirtuallab/matgl#218]
### Problem

In matgl.ext.ase, Berendsen thermostat is implemented for molecular dynamics. However, 
according to this paper, it has been recommended that usage of the Berendsen thermostat 
be discontinued in almost all cases except for replication of prior studies. 

Braun, E.; Moosavi, S. M.; Smit, B. (2018). "Anomalous Effects of Velocity Rescaling Algorithms: 
The Flying Ice Cube Effect Revisited". Journal of Chemical Theory and Computation. 14 (10): 5262–5272.
https://doi.org/10.1021/acs.jctc.8b00446 

### Proposed Solution

Whether the anomalous effects of velocity rescaling algorithms are rare cases or not 
might be not self-evident. It would be highly appreciated if other thermostats are implemented
for molecular dynamics using matgl. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shyuep** [comment]
Other thermostats are actually implemented. See https://github.com/materialsvirtuallab/matgl/blob/096f512e852bc2a5bd454775d1b890404f559fbc/src/matgl/ext/ase.py#L343
