### ISSUE TITLE
what are the outputted units for stress?

### ISSUE THREAD

**Issue by matthewkuner** [materialsvirtuallab/matgl#222]
https://github.com/materialsvirtuallab/matgl/blob/c99288e49f3bb83bf3381888581a877c88ce96d7/src/matgl/ext/ase.py#L208

when using the pre-trained M3GNet ("M3GNet-MP-2021.2.8-PES"), does the linked line of code mean the outputted stresses have units of eV/A^3?

**Comment by shyuep** [comment]
Yes. @kenko911 Pls confirm.

**Comment by kenko911** [comment]
@matthewkuner  I assume you are asking the default output unit for M3GNetCalculator, where the unit of stress is GPa to be consistent with outputs from MatGL. Certainly, you can change the unit into eV/A^3 via modifying corresponding conversion factor. As for the Relaxer and MolecularDynamics, both default units are in the unit of eV/A^3
