### ISSUE TITLE
Does the example training script work for multi-gpu training?

### ISSUE THREAD

**Issue by matthewkuner** [materialsvirtuallab/matgl#224]
https://github.com/materialsvirtuallab/matgl/blob/c99288e49f3bb83bf3381888581a877c88ce96d7/examples/Training%20a%20M3GNet%20Potential%20with%20PyTorch%20Lightning.ipynb#L1

Does the example training script for m3gnet potentials (linked) work for multi-gpu training? I'm specifically curious about fine-tuning it, though I'm guessing the answer is the same whether fine-tuning or training from scratch.

If multi-gpu training is not currently supported, are there plans to support it in the future?

**Comment by shyuep** [comment]
I would think it is no different. Multi-GPU is supported for sure.
