### ISSUE TITLE
TensorNet

### ISSUE THREAD

**Issue by guillemsimeon** [materialsvirtuallab/matgl#229]
Hi,

thanks for considering TensorNet. I was curious to know if you tried to train the model on materials datasets. Btw, I saw that you are not including our 'expnorm' radial basis functions, and TensorNet's performance has not been tested with gaussian or bessel bases.

Thank you,
Guillem

**Comment by kenko911** [comment]
Hi @guillemsimeon, thank you very much for your questions, I did some preliminary training for some periodic systems and it works quite well. We will provide some pre-trained models of TensorNet and SO3Net PESs ASAP.
