### ISSUE TITLE
[Question] M3GNet finetuning and MD

### ISSUE THREAD

**Issue by jhkimmmmm** [materialsvirtuallab/matgl#251]
Hello.
I want to use finetuend M3GNet  for molecular dynamics simulation. 

So, I practiced the examples in https://matgl.ai/ site.
I followed up this tutorials https://matgl.ai/tutorials%2FTraining%20a%20M3GNet%20Potential%20with%20PyTorch%20Lightning.html in google colab server. (I checked that the code working.)

After finetuning the model based on pretrained model (SiO), however, the MD simulation with the potential was not working. 
The error message is below..

![image](https://github.com/materialsvirtuallab/matgl/assets/168813347/81fb0d59-4320-4481-bee6-ee90fa9483be)

How can I fix this problem..?

Thanks.

**Comment by SmallBearC** [comment]
I think you have saved a wrong model. You should save a potential model, but not a m3gnet model.

**Comment by kenko911** [comment]
Hi @jhkimmmmm, the previous example just save the M3GNet class but not Potential class. Please follow the latest example for M3GNet potential training and it should work.
