### ISSUE TITLE
UserWarrning in `_basis.py`

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsvirtuallab/matgl#258]
### Version

1.1.1

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [X] Linux

### What happened?

When running a model, the following `UserWarning` is raised in `matgl.layers._basis.py`:

```
.../site-packages/matgl/layers/_basis.py:121: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  root = torch.tensor(roots[i])
```

Pretty self-explanatory; line 121 needs updating in `_basis.py`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kenko911** [comment]
Hi @Andrew-S-Rosen, thanks for reporting this and I have fixed it in the latest update!
