### ISSUE TITLE
[Feature Request]: Update `pytorch_lightning` to `lightning`

### ISSUE THREAD

**Issue by CompRhys** [materialsvirtuallab/matgl#268]
### Problem

`pytorch_lightning` is being deprecated in favour of `lightning` see: https://github.com/Lightning-AI/pytorch-lightning/discussions/16688

### Proposed Solution

The whole name change is a bit of a mess but the seemingly quickest way out of the mess is for more packages to drop `pytorch_lightning` and move to using `lightning`.

Happy to make a PR for this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shyuep** [comment]
This is done. All tests pass but let me know if there are any further issues.
