### ISSUE TITLE
FYI: There are no 1.1.2 PyPI wheels

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsvirtuallab/matgl#269]
### Version

1.1.2

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [ ] Linux

### What happened?

I saw matgl 1.1.2 was released on GitHub, but there is no corresponding set of wheels on PyPI.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shyuep** [comment]
Should be done.
