### ISSUE TITLE
[Bug]: replace deprecated `ExpCellFilter`

### ISSUE THREAD

**Issue by janosh** [materialsvirtuallab/matgl#274]
### Version

1.1.2

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [ ] Linux

### What happened?

`matGL` still uses the deprecated `ExpCellFilter` which [incorrectly computes cell gradients](https://gitlab.com/ase/ase/-/merge_requests/3024), resulting in inferior convergence behavior

https://github.com/materialsvirtuallab/matgl/blob/eacafa31c12a4c7894320a827dfb1e8e5ea43c65/src/matgl/ext/ase.py#L19

it should be replaced by `FrechetCellFilter` which was added 9 months ago. see related chgnet PR https://github.com/CederGroupHub/chgnet/pull/101

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kenko911** [comment]
Hi @janosh, thank you for reporting the issue, will make a PR soon!

**Comment by kenko911** [comment]
@janosh Done! I set using  FrechetCellFilter as default but I also leave options for users to choose ExpCellFilter for reproducibility.
