### ISSUE TITLE
What are the units of stress in matgl models ?

### ISSUE THREAD

**Issue by txy159** [materialsvirtuallab/matgl#286]
Dear developers,

I was wondering what the units of stress are used in various models in matgl. Which unit should I use for training stress? What is the unit of the outputs from predict_structure methods ?

Thanks.

**Comment by kenko911** [comment]
Hi @txy159, the unit of stress used in MatGL is GPa, as documented in the training section. The unit of the outputs from the predict_structure method depends on the target properties you trained. It can be arbitrary.

**Comment by txy159** [comment]
> Hi @txy159, the unit of stress used in MatGL is GPa, as documented in the training section. The unit of the outputs from the predict_structure method depends on the target properties you trained. It can be arbitrary.

Hi @kenko911,

Could you please clarify where the document is? When training, should the stress used be -0.1 x the stress from VASP or just the stress output from VASP ?

Also, what about the stress unit in other models, such as CHGNet? I found that in CHGNet, the stress used for training is simply the stress from the VASP output.

Thanks.
