### ISSUE TITLE
How to get the property offset of the pre-trained models ?

### ISSUE THREAD

**Issue by txy159** [materialsvirtuallab/matgl#287]
Dear Developers,

I am trying to hyper-tune a potential based on the M3GNet model. I noticed that in the M3GNet paper, the authors first fitted elemental reference energies and subtracted these reference energies from the total energies to improve the M3GNet model's training stability.

I loaded the pre-trained model using the following code, but I couldn't retrieve the information on the elemental reference energies.

<img width="533" alt="image" src="https://github.com/user-attachments/assets/0cf1207b-576e-4ac1-96d5-767ac728811f">

The outputs:

<img width="272" alt="image" src="https://github.com/user-attachments/assets/118870aa-09da-4f92-a02b-93ff766abde7">

Could you please illustrate how to obtain these elemental reference energies? If I would like to hyper-tune a pre-trained model on a new database so that the new model works on both the new and the original datasets, is it necessary to keep the elemental reference energies unchanged during the hyper-tuning process? Could you please provide some example code for this? It seems that no examples have been given for this.

Thanks.

**Comment by txy159** [comment]
Also, could you please reply to my previous comment ? #286 

Thanks a lot !

**Comment by kenko911** [comment]
Hi @txy159, the official documentation is available at https://matgl.ai/, and you can also find it on the main page of our GitHub repository. Please read through the "Model Training" section for instructions on stress conversion from VASP, as all architectures in MatGL follow the same guidelines. I have also added a demonstration of obtaining and using element offsets from a pre-trained model for fine-tuning in the M3GNet potential training notebook. Finally, I cannot give you an exact answer whether it is necessary to keep the elemental reference energies unchanged during the hyper-tuning process. You should try both options to see if it improves training and validation errors for your dataset. Thanks!
