### ISSUE TITLE
[Bug]: Cannot run tutorial 

### ISSUE THREAD

**Issue by yaomz16** [materialsvirtuallab/matgl#292]
### Version

1.1.2

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [X] Linux

### What happened?

I'm trying to run the tutorial shown in https://matgl.ai/tutorials%2FTraining%20a%20MEGNet%20Formation%20Energy%20Model%20with%20PyTorch%20Lightning.html, however there are two bugs: one is `from matgl.graph.data import MGLDataset, MGLDataLoader, collate_fn`, `collate_fn_graph` instead of `collate_fn` should be imported, this one is easy to fix. 

However, I got the following error when running `trainer.fit(model=lit_module, train_dataloaders=train_loader, val_dataloaders=val_loader)`, it's basically saying `lit_module` has to be `pl.LightningModule` instead of `ModelLightningModule`. 

How can I fix this issue? And can you update the tutorial on the website , thank you.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kenko911** [comment]
Hi @yaomz16, thank you very much for reporting the issues. I will update the notebook accordingly. I think the second problem comes from the version of PyTorch-Lightning and Lightning. Please try installing Lightning>=2.2.5 to see if the problem still exists.

**Comment by yliu1240** [comment]
Hi, all!
        I encountered this issue as well. It seems not directly related to the versions of PyTorch_lightning and lightning but to their codes' implementation. In my case, I kept having the issue with PyTorch_lightning = 2.3.0 and lightning = 2.4.0 (the issue persists after I update PyTorch_lightning = 2.4.0). In the end, I get around the issue by using the 'Trainer' from lightning.torch:
        >>> import lightning as pl # previously pytorch_lightning as pl
        >>> trainer = pl.Trainer(...)
or
        >>> from lightning.pytorch import Trainer # you can preserve "import pytorch_lightning as pl" using this approach
        >>> trainer = Trainer(...)
        
        It's quite interesting here since lightning.pytorch and pytorch_lightning are actually the same (their trainer.py and compile.py codes look the same)
        
        I hope this may help.
Best regards,
