### ISSUE TITLE
[Feature Request]: Remove torch<=2.2.1 upper bound

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsvirtuallab/matgl#296]
### Problem

In `pyproject.toml`, there is a `torch<=2.2.1` upper bound on `torch`. I imagine this was likely due to https://github.com/dmlc/dgl/issues/7247, which seems to be resolved now. According to the changelog, `dgl` 2.3.0 supports `torch` 2.3.1.

CC @zulissimeta.

### Proposed Solution

Update `pyproject.toml` and pray.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kenko911** [comment]
Hi @Andrew-S-Rosen, thank you for your information and I just removed it!

**Comment by DanielYang59** [comment]
I haven't tested other versions of `torch` but it appears `torch==2.4.1` is having this issue again https://github.com/materialsproject/pymatgen/pull/4101#issuecomment-2404278607
