### ISSUE TITLE
matgl 1.1.3 not on PyPI

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsvirtuallab/matgl#299]
### Version

1.1.3

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [ ] Linux

### What happened?

Just a head's up --- I don't think 1.1.3 made its way to PyPI. Looks like the version wasn't updated from 1.1.2: https://github.com/materialsvirtuallab/matgl/actions/runs/10274697423/job/28432323099, which can be seen in `main`: 

https://github.com/materialsvirtuallab/matgl/blob/f3afb34ef786a218e7a3551afc88ff57618888fa/pyproject.toml#L60

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kenko911** [comment]
Hi @Andrew-S-Rosen, sorry for the late reply. Thank you very much for your reminder and I have fixed it. Could please check if now it works? Thanks a lot! :)

**Comment by Andrew-S-Rosen** [comment]
All good now! Thanks! Closing this issue.

**Comment by Andrew-S-Rosen** [comment]
@kenko911: Actually, I am getting a graphbolt issue. Do you know what it is offhand? https://github.com/Quantum-Accelerators/quacc/actions/runs/10285492623/job/28463890868?pr=2393#step:5:441
