### ISSUE TITLE
pytorch lightning support

### ISSUE THREAD

**Issue by JonathanSchmidt1** [materialsvirtuallab/matgl#33]
Dear everyone,

First off all thank you for taking the time to convert  m3gnet to pytorch. I was wondering if there are any aspirations to build a pytorch lightning module for m3gnet which would trivialize multigpu/ multinode and mixed precision training?

best wishes,
Jonathan

**Comment by JonathanSchmidt1** [comment]
I did it for pytorch geometric a few times and it is usually quite simple as you basically drop in the model definition, training, validation  and test step definitions into the lightning module and then you just call it with trainer =pl.Trainer(training_options) and trainer.fit(model=LitM3gnet, train_dataloader = dataloader) etc... 
Mostly you remove all the .to(device) calls or datatype calls and that's it if one is lucky ;).
I have no experience with the DGL but https://github.com/IntelLabs/matsciml is using pytorch lightning successfully with dgl for the OCP so it can definitely be done. 
If you should start to work on an implementation, maybe can you mention it here? A master student in our group who needs several force field codes with multi node training support might also start implementing it. If he starts working on it, I will also update this issue so the work is not duplicated.

**Comment by shyuep** [comment]
@JonathanSchmidt1 Thanks! Yes we are actually collaborating with the autors of matsciml on this repo. So we should be able to get this done relatively quickly.

**Comment by shyuep** [comment]
This has been implemented by @kenko911. See matgl.trainers._trainer.
