### ISSUE TITLE
[Feature Request]: Add CHGNet blurb to README.md and intro doc.

### ISSUE THREAD

**Issue by shyuep** [materialsvirtuallab/matgl#340]
### Problem

Please add the fact that MatGL includes CHGNet from @BowenD-UCB in the README and intro docs.

### Proposed Solution

Include a writeup on CHGNet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kenko911** [comment]
Hi @shyuep, thanks for your reminder! I will also include an example to call PESCalculator using CHGNet and get it by this week. Thanks!

**Comment by kenko911** [comment]
I included more descriptions of using CHGNet pretrained models in the jupyter-notebook in the latest PR.

**Comment by BowenD-UCB** [comment]
Thanks for the reminder! I will work with Kenko on putting together an example
