### ISSUE TITLE
[Feature Request]: The collate_fn function is no longer supported in the latest version

### ISSUE THREAD

**Issue by Long-Brian-Yang** [materialsvirtuallab/matgl#434]
### Problem

The `collate_fn` function is no longer supported in the latest version of MatGL library, which causes ImportError when trying to use MGLDataLoader for batch processing training data. This breaking change affects the training workflow that was previously working in older versions.

### Proposed Solution

Reintroduce the `collate_fn` in the MatGL library

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kenko911** [comment]
Hi @Long-Brian-Yang , We introduced  collate_fn_graph and collate_fn_pes for structural properties and MLIPs in the latest released version, respectively.

**Comment by Long-Brian-Yang** [comment]
I got it. Thank you for your relpy.
