### ISSUE TITLE
no such file or directory: "../../pretrained/MP-2021.2.8-EFS/m3gnet.pt"

### ISSUE THREAD

**Issue by matthewkuner** [materialsvirtuallab/matgl#44]
https://github.com/materialsvirtuallab/matgl/blob/aaab746f70722317b47d740cc32a13b9cd6d8937/matgl/models/m3gnet.py#L245

When I try to load the pretrained m3gnet potential, I get the following error:

> FileNotFoundError: [Errno 2] No such file or directory: '/Users/kuner/opt/anaconda3/envs/atomate2/lib/python3.9/site-packages/matgl/models/../../pretrained/MP-2021.2.8-EFS/m3gnet.pt'

It seems like all of the necessary files are currently not being distributed with the package (note I installed this via 'pip install matgl'). Any help would be appreciated!

**Comment by kenko911** [comment]
Hi, we will provide the pretrained model ASAP when we finished the benchmarking and optimization of the model. if you want to use the pretrained model now, please go to the m3gnet repo. Thanks.

**Comment by matthewkuner** [comment]
@kenko911 should we expect this repo to become the primary place for m3gnet development (if any is planned)?

**Comment by shyuep** [comment]
@matthewkuner Yes it is the primary place for m3gnet development. The architecture has already been implemented. We are still making some code improvements. @kenko911 is running the fitting of models and the pre-trained models will be uploaded soon.

**Comment by shyuep** [comment]
The m3gnet potential has been pushed to the repo.
