### ISSUE TITLE
[ASE Atoms] work with ASE Atoms from non-periodic molecules

### ISSUE THREAD

**Issue by yliu1240** [materialsvirtuallab/matgl#442]
Hi, all!
        I'm learning the MatGL recently and I may want to work with ASE Atoms objects that are generated from non-periodic molecules. It seems the tutorials are mainly about using Pymatgen periodic structures, like MGLDataset. Since there are tools in matgl.ext.ase (Atoms2Graph) and pymatgen.core.structure.molecule, I'm wondering if I can leverage these tools to directly work from ASE Atoms or do I need to write some customized classes, such as replacing current MGLDataset which is based on Pymatgen structures?
        Is it possible to have any rough guidance?
        
Thank you in advance!
Best regards,

**Comment by kenko911** [comment]
Hi @yliu1240, you can just use Molecule2Graph to convert pymatgen Molecule object to DGL graphs. Other things work exactly the same with periodic cases. You always can convert ASE into pymatgen object. Please read the documentation carefully and you should be able to figure it out. Thanks!

**Comment by yliu1240** [comment]
Hi @kenko911, thank you so much!
