### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by msehabibur** [materialsvirtuallab/matgl#448]
### Email (Optional)

rahma103@purdue.edu

### Problem

I have generated a DFT dataset using HSE functional. Since the MATGL model is mainly trained on PBE data, can I fine-tune the initial MATGL model with my HSE data? Will it work?

### Proposed Solution

I am not sure. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shyuep** [comment]
Short answer is yes. You can also try using a multi-fidelity approach like the one shown in this https://arxiv.org/abs/2409.00957

**Comment by msehabibur** [comment]
@shyuep Thank you! But, can you please explain a bit further? For example, do I need to fine-tune the PBE model with HSE data? Do I have to do anything else, like do I have shift elemental energy reference?

**Comment by shyuep** [comment]
Please read the paper first.

**Comment by msehabibur** [comment]
@shyuep thank you! I read that paper, it seems like the fidelity information is added as a vector in the global state feature input to the m3gnet model. However, the code implementation has not been clarified in the paper.

**Comment by kenko911** [comment]
Hi @msehabibur, we are currently optimizing the code and will provide an example soon. Regarding fine-tuning, it largely depends on the actual differences between the two PESs. I suggest trying both approaches—with and without shifting the elemental energy reference.
