### ISSUE TITLE
[Bug]: KeyError: 'forces' when running trainer in training_m3gnet_potential.py

### ISSUE THREAD

**Issue by Long-Brian-Yang** [materialsvirtuallab/matgl#450]
### Version

v2023.1.1

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [ ] Linux

### What happened?

When running the training_m3gnet_potential.py script, an error occurs during the validation phase (val_loop.run()), causing the program to terminate. The issue arises in the collate_fn_pes function within the file matgl/graph/data.py, specifically at the line f = torch.vstack([d["forces"] for d in labels]), where a KeyError: 'forces' is raised. This suggests that some entries in the labels dictionary are missing the key 'forces'.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kenko911** [comment]
Hi @Long-Brian-Yang, I am unable to reproduce the errors you encountered based on the given information. There is no script for reference and even the reported version of MatGL seems not correct...
