### ISSUE TITLE
No such file or directory: '/usr/local/lib/python3.10/dist-packages/matgl/models/../../pretrained/MP-2018.6.1-Eform/megnet.pt'

### ISSUE THREAD

**Issue by Preyansh1112** [materialsvirtuallab/matgl#47]
Respected Authors
First of all, thank you for creating this wonderful library.
I am facing the same issue as the previous issue opened, but for MEGNET. I use pip install downloading matgl.
On the website, it is mentioned that pre-trained MEGNet models now available for formation energies and band gaps. I am trying to predict the band gaps, but got stuck in the implementation.

**Comment by shyuep** [comment]
We just released v0.2.1 which should fix this problem. Pls force a reinstall of the latest version. Thanks.
