### ISSUE TITLE
Structure relaxation

### ISSUE THREAD

**Issue by Asif-Iqbal-Bhatti** [materialsvirtuallab/matgl#68]
Hello, 

Thank you for making the code accessible. I want to inform with M3GNET i was able to relax the structure but when I switch to MATGL module the structure is not relaxing rather displaying large force. 

I am testing this potential on HfNbTaTiZr High entropy alloys to study the core structure of  screw dislocation in BCC structure. With M3GNET the relaxation was with 200 steps but with MATGL it takes 1000 steps but the forces on the structure keeps on increasing and then the terminal hangs on. Is the module on testing stage yet?

Thanks

**Comment by shyuep** [comment]
Thanks for reporting this. We have not tested on HEAs. If you are able to provide an example file, we can investigate.

**Comment by janosh** [comment]
@Asif-Iqbal-Bhatti You can either zip the POSCAR file to upload it or paste it here in plain text, preferably inside HTML `<details>`:

<details><summary>POSCAR</summary>

```txt
POSCAR generated from bestsqs
3.0
 5.000000000  0.000000000  0.000000000
 0.000000000  5.000000000  0.000000000
 0.000000000  0.000000000  5.000000000
Hf    Nb    Ta    Ti    Zr    
  50  50  50  50  50
Direct      
 0.800000000  0.800000000  0.200000000
 0.800000000  1.000000000  0.200000000
 0.700000000  0.900000000  0.100000000
 0.800000000  0.600000000  0.400000000
 0.600000000  0.400000000  0.200000000
 0.600000000  0.800000000  0.400000000
 0.700000000  0.700000000  0.500000000
 0.800000000  0.400000000  0.600000000
 0.700000000  0.300000000  0.500000000
 0.400000000  1.000000000  0.200000000
 0.300000000  0.900000000  0.100000000
 0.500000000  0.900000000  0.300000000
 0.100000000  0.700000000  0.100000000
 0.400000000  0.600000000  0.400000000
 0.300000000  0.500000000  0.300000000
 0.800000000  0.800000000  0.800000000
 0.700000000  0.500000000  0.700000000
 0.500000000  0.300000000  0.500000000
 0.100000000  0.900000000  0.100000000
 0.800000000  0.400000000  0.800000000
 0.600000000  1.000000000  0.600000000
 1.000000000  0.800000000  0.200000000
 0.200000000  0.600000000  0.400000000
 1.000000000  0.400000000  0.200000000
 0.400000000  0.600000000  0.600000000
 0.900000000  0.100000000  0.100000000
 0.700000000  0.700000000  0.900000000
 0.600000000  0.400000000  0.800000000
 0.600000000  0.200000000  0.800000000
 0.300000000  0.700000000  0.700000000
 0.200000000  0.600000000  0.600000000
 1.000000000  0.400000000  0.400000000
 0.900000000  0.100000000  0.300000000
 0.200000000  0.200000000  0.600000000
 0.900000000  0.900000000  0.300000000
 0.200000000  1.000000000  0.600000000
 0.600000000  0.200000000  1.000000000
 0.500000000  0.900000000  0.900000000
 0.900000000  0.700000000  0.500000000
 0.100000000  0.700000000  0.700000000
 0.100000000  0.500000000  0.700000000
 0.200000000  0.400000000  0.800000000
 0.100000000  0.900000000  0.700000000
 0.900000000  0.700000000  0.700000000
 0.900000000  0.300000000  0.700000000
 0.200000000  0.400000000  1.000000000
 0.100000000  0.300000000  0.900000000
 1.000000000  0.800000000  1.000000000
 1.000000000  0.600000000  1.000000000
 0.900000000  0.100000000  0.900000000
 0.800000000  0.600000000  0.200000000
 0.700000000  0.500000000  0.100000000
 0.500000000  0.300000000  0.100000000
 0.500000000  0.100000000  0.100000000
 0.700000000  0.900000000  0.300000000
 0.700000000  0.500000000  0.500000000
 0.300000000  0.100000000  0.100000000
 0.500000000  0.100000000  0.300000000
 0.800000000  1.000000000  0.600000000
 0.300000000  0.700000000  0.300000000
 0.200000000  0.600000000  0.200000000
 0.100000000  0.500000000  0.100000000
 0.100000000  0.300000000  0.100000000
 0.700000000  0.700000000  0.700000000
 0.400000000  0.400000000  0.400000000
 0.200000000  0.200000000  0.200000000
 0.700000000  0.100000000  0.700000000
 0.500000000  0.900000000  0.500000000
 0.100000000  0.700000000  0.300000000
 1.000000000  0.600000000  0.200000000
 0.500000000  0.500000000  0.700000000
 1.000000000  1.000000000  0.200000000
 0.200000000  1.000000000  0.400000000
 0.100000000  0.900000000  0.300000000
 0.800000000  0.400000000  1.000000000
 0.400000000  1.000000000  0.600000000
 0.700000000  0.100000000  0.900000000
 0.800000000  1.000000000  1.000000000
 0.100000000  0.700000000  0.500000000
 0.100000000  0.500000000  0.500000000
 0.500000000  0.500000000  0.900000000
 0.400000000  0.400000000  0.800000000
 0.300000000  0.300000000  0.700000000
 0.400000000  0.200000000  0.800000000
 0.600000000  1.000000000  1.000000000
 1.000000000  0.800000000  0.600000000
 0.200000000  0.800000000  0.800000000
 1.000000000  0.600000000  0.600000000
 0.400000000  0.800000000  1.000000000
 0.200000000  0.600000000  0.800000000
 0.900000000  0.300000000  0.500000000
 0.900000000  0.100000000  0.500000000
 0.400000000  0.400000000  1.000000000
 1.000000000  1.000000000  0.600000000
 0.900000000  0.900000000  0.500000000
 1.000000000  0.600000000  0.800000000
 0.900000000  0.900000000  0.700000000
 0.200000000  1.000000000  1.000000000
 0.900000000  0.300000000  0.900000000
 1.000000000  0.200000000  1.000000000
 0.700000000  0.500000000  0.300000000
 0.800000000  0.400000000  0.400000000
 0.700000000  0.300000000  0.300000000
 0.500000000  0.900000000  0.100000000
 0.400000000  0.600000000  0.200000000
 0.500000000  0.500000000  0.300000000
 0.400000000  0.400000000  0.200000000
 0.300000000  0.300000000  0.100000000
 0.600000000  0.400000000  0.400000000
 0.600000000  0.200000000  0.400000000
 0.700000000  0.100000000  0.500000000
 0.600000000  1.000000000  0.400000000
 0.200000000  0.800000000  0.200000000
 0.500000000  0.500000000  0.500000000
 0.100000000  0.100000000  0.100000000
 0.200000000  1.000000000  0.200000000
 0.700000000  0.300000000  0.700000000
 0.600000000  0.200000000  0.600000000
 0.300000000  0.900000000  0.300000000
 0.800000000  1.000000000  0.800000000
 0.900000000  0.500000000  0.100000000
 0.500000000  0.700000000  0.700000000
 0.300000000  0.500000000  0.500000000
 0.600000000  0.600000000  0.800000000
 0.200000000  0.200000000  0.400000000
 0.100000000  0.100000000  0.300000000
 0.900000000  0.900000000  0.100000000
 0.700000000  0.500000000  0.900000000
 0.400000000  0.200000000  0.600000000
 0.700000000  0.300000000  0.900000000
 0.500000000  0.100000000  0.700000000
 0.600000000  1.000000000  0.800000000
 0.900000000  0.700000000  0.300000000
 0.200000000  0.800000000  0.600000000
 0.400000000  0.800000000  0.800000000
 0.600000000  0.600000000  1.000000000
 0.300000000  0.700000000  0.900000000
 0.300000000  0.500000000  0.900000000
 1.000000000  0.200000000  0.600000000
 0.200000000  1.000000000  0.800000000
 0.300000000  0.900000000  0.900000000
 0.200000000  0.800000000  1.000000000
 0.200000000  0.600000000  1.000000000
 0.100000000  0.500000000  0.900000000
 0.900000000  0.100000000  0.700000000
 0.100000000  0.100000000  0.900000000
 0.900000000  0.700000000  0.900000000
 0.900000000  0.500000000  0.900000000
 1.000000000  0.400000000  1.000000000
 0.900000000  0.900000000  0.900000000
 0.700000000  0.700000000  0.100000000
 0.700000000  0.300000000  0.100000000
 0.700000000  0.100000000  0.100000000
 0.600000000  0.800000000  0.200000000
 0.500000000  0.700000000  0.100000000
 0.800000000  0.800000000  0.400000000
 0.600000000  0.600000000  0.200000000
 0.600000000  0.200000000  0.200000000
 0.700000000  0.100000000  0.300000000
 0.600000000  1.000000000  0.200000000
 0.400000000  0.800000000  0.200000000
 0.300000000  0.700000000  0.100000000
 0.800000000  0.800000000  0.600000000
 0.600000000  0.600000000  0.400000000
 0.500000000  0.300000000  0.300000000
 0.700000000  0.900000000  0.500000000
 0.600000000  0.800000000  0.600000000
 0.600000000  0.600000000  0.600000000
 0.400000000  0.200000000  0.400000000
 0.800000000  0.200000000  0.800000000
 0.700000000  0.900000000  0.700000000
 0.900000000  0.700000000  0.100000000
 0.200000000  0.800000000  0.400000000
 0.300000000  0.700000000  0.500000000
 0.900000000  0.300000000  0.100000000
 0.600000000  0.800000000  0.800000000
 0.400000000  0.400000000  0.600000000
 0.300000000  0.100000000  0.500000000
 0.300000000  0.900000000  0.500000000
 0.500000000  0.900000000  0.700000000
 0.700000000  0.900000000  0.900000000
 1.000000000  0.600000000  0.400000000
 0.600000000  0.800000000  1.000000000
 0.400000000  0.600000000  0.800000000
 0.200000000  0.400000000  0.600000000
 0.100000000  0.300000000  0.500000000
 1.000000000  1.000000000  0.400000000
 0.600000000  0.400000000  1.000000000
 0.300000000  0.100000000  0.700000000
 0.500000000  0.100000000  0.900000000
 0.400000000  1.000000000  0.800000000
 0.300000000  0.300000000  0.900000000
 0.300000000  0.100000000  0.900000000
 0.400000000  1.000000000  1.000000000
 0.100000000  0.700000000  0.900000000
 0.900000000  0.500000000  0.700000000
 1.000000000  0.200000000  0.800000000
 0.200000000  0.200000000  1.000000000
 1.000000000  1.000000000  0.800000000
 1.000000000  1.000000000  1.000000000
 0.800000000  0.400000000  0.200000000
 0.800000000  0.200000000  0.200000000
 0.700000000  0.700000000  0.300000000
 0.500000000  0.500000000  0.100000000
 0.800000000  0.200000000  0.400000000
 0.800000000  1.000000000  0.400000000
 0.500000000  0.700000000  0.300000000
 0.300000000  0.500000000  0.100000000
 0.800000000  0.600000000  0.600000000
 0.400000000  0.200000000  0.200000000
 0.800000000  0.200000000  0.600000000
 0.400000000  0.800000000  0.400000000
 0.500000000  0.700000000  0.500000000
 0.200000000  0.400000000  0.200000000
 0.300000000  0.300000000  0.300000000
 0.800000000  0.600000000  0.800000000
 0.600000000  0.400000000  0.600000000
 0.300000000  0.100000000  0.300000000
 0.500000000  0.100000000  0.500000000
 0.400000000  1.000000000  0.400000000
 0.400000000  0.800000000  0.600000000
 0.100000000  0.500000000  0.300000000
 0.200000000  0.400000000  0.400000000
 0.100000000  0.300000000  0.300000000
 1.000000000  0.200000000  0.200000000
 0.800000000  0.800000000  1.000000000
 0.300000000  0.300000000  0.500000000
 0.800000000  0.600000000  1.000000000
 0.500000000  0.300000000  0.700000000
 0.800000000  0.200000000  1.000000000
 1.000000000  0.800000000  0.400000000
 0.900000000  0.500000000  0.300000000
 0.900000000  0.300000000  0.300000000
 0.500000000  0.700000000  0.900000000
 0.300000000  0.500000000  0.700000000
 1.000000000  0.200000000  0.400000000
 0.100000000  0.100000000  0.500000000
 0.500000000  0.300000000  0.900000000
 0.100000000  0.900000000  0.500000000
 0.300000000  0.900000000  0.700000000
 0.900000000  0.500000000  0.500000000
 1.000000000  0.400000000  0.600000000
 0.400000000  0.600000000  1.000000000
 0.100000000  0.300000000  0.700000000
 0.200000000  0.200000000  0.800000000
 0.100000000  0.100000000  0.700000000
 0.400000000  0.200000000  1.000000000
 1.000000000  0.800000000  0.800000000
 1.000000000  0.400000000  0.800000000
 0.100000000  0.900000000  0.900000000
```
</details> 

Hint: Type `/details` in the commend field for GitHub to autocomplete the `<details>` tag for you.

**Comment by Asif-Iqbal-Bhatti** [comment]
<details><summary>Details</summary>
<p>

Hf Nb Ta Ti Zr 
 1.0000000000000000
    17.1104824359576853   -0.0022035520747334   -0.0416481878837009
    -0.0022035520752459   17.0941736581454400    0.0130913452030956
    -0.0416481878840739    0.0130913452021908   17.0537157858369781
 Hf  Nb  Ta  Ti  Zr 
  50  50  50  50  50
Cartesian
 13.7166506662841634 13.5479994276223490  3.2880482185290996
 13.5509650876264107 17.0953512260134914  3.3100993349812424
 11.7306308949684031 15.3297742850969172  1.6867729438680195
 13.5981044863431588 10.2057000596983940  6.7023898114953564
 10.2225873265635663  6.8017706171040899  3.4772403531443352
 10.4162890951592040 13.9989817989332082  6.8962364660775659
 11.9481855106105623 11.9607521048609851  8.6384736515042508
 13.6727268048595842  6.8163568340511045 10.2458909835681435
 11.8639975719845481  5.1435251809735059  8.4019031181537365
  6.8042423080293757 17.0940766104676491  3.4240602054596216
  5.0796030449373619 15.4405379690609621  1.6484868390535661
  8.6366873434096476 15.4580722301471045  4.9760624954467048
  1.8942852035342388 11.9465865496817365  1.7013092343114364
  6.8346805225451837 10.2571421726439826  6.8442658129786000
  5.2626096279763122  8.6066345817345233  5.0196350911243952
 13.5377600148746549 13.8166641087535691 13.6408904961534603
 11.8367973718898440  8.6689730339980180 11.8671496327375081
  8.4914962809164329  5.0613553601730201  8.4708999507340668
  1.7369526854667383 15.4531356964092037  1.6587257629312884
 13.6445370273372077  6.8688553629160607 13.6872087769909605
 10.3220276673521987 16.9996516742114494 10.3642704851118452
 17.0997174888968395 13.6719509131425774  3.3869831751548412
  3.4925778948299064 10.3989628579447295  6.8354502076327091
 17.1582689555394232  6.8811905368963941  3.1075160795597023
  6.8983119698530988 10.3139148088527364 10.1528185048122914
 15.4226019752242891  1.5314815136545465  1.5707844054440629
 11.6637212652138356 12.0917654269292747 15.2649080459579256
 10.2350513974952371  6.8868152494654709 13.6642074194293617
 10.1701735376379219  3.2903940396007347 13.6226033080231872
  5.1777179318742119 11.9960469356717887 12.1328076885544611
  3.4787484724949964 10.3676342874119776 10.0818856786493338
 17.1920963370206294  6.7421727810666425  6.9783247724214990
 15.4877017441764249  1.5404751833391483  5.0895526578929191
  3.5621649014758190  3.3727848685467348 10.2650038610125485
 15.3361623453377884 15.3958552900702390  5.1185695297829277
  3.7476521264918135 17.1802977269549970 10.1552914563640950
 10.1891351966163377  3.2765158084090311 17.0589922829528078
  8.5836082397986964 15.3208157032749419 15.5157885347249547
 15.3728950003262987 12.1286602490223139  8.4702939591300037
  1.7489568699741542 12.0423463559103414 11.9300476444115695
  1.7401545139174224  8.6985517625761943 11.9136545906637998
  3.4807828454943417  6.8641614857666520 13.7330271799525363
  1.7630695871930295 15.4689404246038826 11.9377891317078593
 15.3411431578387365 12.1049383076769086 11.8473223152818488
 15.4306165878962549  4.9024712920911551 12.0464944652367141
  3.3860715496534182  6.8963873546801748 16.9834297336956688
  1.5251952637637058  4.9757670886292926 15.4578275833810483
 16.9230531689479555 13.6526939885620866 17.0037235320392988
 17.0664979112481205 10.2768230099380702 16.9293156839135186
 15.2997268128561501  1.7100798883882176 15.2381520830792425
 13.7668772288710493 10.2134977616009994  3.3478714686300743
 11.9908441593744008  8.5347810493239376  1.6408127437580682
  8.4794046666286853  5.1375924603446110  1.6508652014039544
  8.5162540933832123  1.6414993337738411  1.7241037135376009
 11.9030052512727718 15.3622356206561470  4.9633829340701014
 11.8488984517396716  8.5363666484322511  8.3849370067976601
  5.0431551659744658  1.6808092701088886  1.6725091693638305
  8.6263251849477012  1.7105366900945380  5.0627545207935247
 13.6514165318509306 17.1193294222296721 10.2744882609046080
  5.0935597969928432 12.0278046515547992  5.0175171015698909
  3.4236413735859990 10.4068942032901663  3.3609494754321583
  1.7045409397052840  8.6384888074424300  1.5860353214591310
  1.7718401865686746  5.0398638135622624  1.5401281121322696
 11.7109270393016125 12.0689379976518261 11.8620896297814848
  7.0215441802324170  6.9703986864885872  6.7544701040313768
  3.3855126011408054  3.3332162775874035  3.2968626530431329
 11.9510373424785943  1.6906009490159704 12.0132725315672975
  8.6234361947169873 15.4713392946397157  8.6128021546667899
  1.7826939217824169 12.0391312870215401  5.1155082011363291
 17.1149603870660876 10.3274003164186539  3.2546741240101804
  8.4430540275275803  8.6267705746132410 12.0066955478389747
 17.2038107557201521 17.0372853029177733  3.3605901063984360
  3.4691591941859734 17.0441773337091149  6.7531915213322860
  1.7903115897201067 15.4451254468363857  5.0962056444924029
 13.7064821985869436  6.8615692902558649 16.9382263555326631
  6.9020485565173937 17.1142563518873381 10.2658567860704313
 12.0036033364522297  1.6704704405956519 15.2672880905898243
 13.4983881134419743 16.9936947054724428 16.9434692683828594
  1.6931991332308813 12.0361905143993315  8.5094994909224297
  1.6852042061621082  8.7844732762065139  8.5853272723926857
  8.4929627471659934  8.5252278507219366 15.3045879829134179
  6.7418655807691232  6.8352076345034449 13.7320474790279494
  5.2205273459312629  5.1872175662444429 11.9036591317308762
  6.7021708146058048  3.4108434868051885 13.5861754610349461
 10.2222535536415471 17.2308075096718589 17.0231396131914678
 17.1051825866414617 13.7557339436124799 10.2045249225085239
  3.4589324450029233 13.6896950182378454 13.7597988935243283
 17.1377483257618870 10.4109635337923958 10.1971695747553071
  6.7159431548694064 13.6989188704886988 17.0329924874488583
  3.3338176282476129 10.3423375433462894 13.8471098718024201
 15.3098146614039621  5.0780767523005679  8.5192448576648250
 15.3636326807720849  1.5696448505996654  8.5518560220182369
  6.6811899518813300  6.8012858750482854 17.0020084149746644
 16.8852856855319082 17.0482777176196052 10.2425630364224727
 15.3226756538177362 15.3955380472721526  8.6197074082280629
 17.0875163726706347 10.2850338138035156 13.6350029840720453
 15.3241734055941876 15.4532271368479304 11.8957032978468877
  3.4237376841308347 17.2031343678541866 16.9840666969328353
 15.3348754978108968  5.1266194695611000 15.3381143888526807
 17.0414832229898252  3.4280598502096309 16.9987334347397194
 11.9431873307403773  8.5152785605047381  5.0451286760421237
 13.4966391194375603  6.8301655775915844  6.8041072375697489
 11.8058814828348186  5.1315597192415172  5.1270718614005970
  8.4732386683070047 15.4755233466565674  1.6436674862457636
  6.8732973366177417 10.3382413257331738  3.4213932761954373
  8.5576524311204221  8.6004897284758872  5.0673449233119889
  6.9564825585336818  6.7942394312090268  3.3894936846657546
  5.0693084418459975  5.0706982946009136  1.6117242353375505
 10.1748645830941360  6.8950205237541269  6.7043745907105450
 10.2496769686651437  3.3924569023389024  6.6833781287047733
 11.8260393289007393  1.6877756802360542  8.6027104549602775
 10.3099239663839271 17.1124310544244906  6.7836834466282561
  3.4084701850832153 13.6954670341963460  3.4332927470789376
  8.5837539049684786  8.5321775365035126  8.5170672439169284
  1.7683335425785673  1.7101338394927228  1.6111691145202149
  3.3189523062947490 17.1429146515596216  3.3834529559210753
 11.9418208731377451  4.9904592356812474 12.0081925273114596
 10.2871490090859457  3.3334491321746658 10.2868217331873293
  4.9517580962852694 15.2928166919167268  5.0224851826894605
 13.5807386677269513 17.0460699836720835 13.6121550013789303
 15.4132848791386650  8.5587122125745978  1.5912207933887117
  8.6364114096704032 11.8603432074694304 11.9909259441630702
  5.1983794366657685  8.4602334454555823  8.5461882160583809
 10.1931425378881340 10.1788472397876202 13.6243004784385224
  3.3913297850426849  3.2771840980289695  6.8769177693630681
  1.7653084413790214  1.5016013924352321  5.0695521060619546
 15.4089759169934748 15.5238002515428555  1.6106844750599802
 11.8551631570187403  8.5133886071823675 15.4419931564359985
  6.7652416501562378  3.1718323603389034 10.3499259441467437
 12.0254756259877826  5.0962726646105594 15.2625740277120894
  8.5480874680760657  1.6476876602735846 11.9315542091352000
 10.3401552690808867 17.0836500359252348 13.7234726119826558
 15.4620378600950055 11.8462444355305898  5.0433883875600962
  3.4564773904141890 13.6576035092789567 10.2111265953473982
  6.7837444508309774 13.7418304330283298 13.7475976955189516
 10.2561027013051227 10.1607461804416861 16.9455191544930912
  5.0852386431644137 12.0340088206754441 15.3553198373215487
  5.1513920926633556  8.6618614592424361 15.3315104995427269
 16.9447420674913722  3.3271101726089181 10.1381325985474433
  3.5082896752252752 17.1579276729144290 13.7809325555769551
  5.1697262333549059 15.4152604477657587 15.3897670777589877
  3.5254635695477994 13.6835252126994096 16.9710386420517167
  3.4256233796238016 10.3599286491440505 17.0064659911370271
  1.7040176472376674  8.6656196305197355 15.4221193618562999
 15.3115424426255657  1.6029450177049440 11.9632192495252330
  1.5719135499355921  1.6607467073433435 15.4159202248729965
 15.3646917664121077 11.9838421652032565 15.2475598157291881
 15.3726919483482387  8.5452763938270042 15.3700925852763550
 17.0263014380145670  6.8623203082865869 16.9934877096332784
 15.3296543345101810 15.5277421107369005 15.3099451099461081
 11.7228897322107102 11.6714870897527483  1.9539276366405847
 11.6619110379228150  5.2993681213176149  1.4605649536959200
 11.7830160968129984  1.5675440552200957  1.6241934685985298
 10.1807918654464213 13.7760289037060843  3.3884127385382432
  8.6778074580819844 12.1122843220569081  1.5899078150007557
 13.6756358254119625 13.7662068971744063  6.8044899388057702
 10.4164505132974714 10.2747569558020491  3.2665479167435953
 10.1510438754515402  3.4334131543973032  3.4640059630440372
 11.6324190307508815  1.6328559882421418  5.0036274251662407
 10.2001541502517856 17.1699015310355776  3.3416207611265865
  6.6693040097700704 13.5267526576276005  3.1866337917130498
  5.2494539354205161 12.1507983642347170  1.8397836361273414
 13.6220019648655875 13.8684899028904454 10.2239803142049137
 10.3160082595948150  9.9456489615702370  6.8001476533124121
  8.5964302735620333  5.1524859338947948  5.1698482899253309
 12.0117646954626291 15.3660773222771709  8.6634704323596452
 10.3604466668570119 13.6672191941795784 10.3651879952117199
 10.1458347496830967 10.2351968045036923 10.3123009375413233
  7.0040755751768593  3.4332984568543274  6.7309114112123316
 13.5433981277950082  3.4275274945525394 13.6280295157215097
 12.0589368585441363 15.4359599750147698 11.9484756429063470
 15.4729346322921373 11.8337470836950605  1.8213177650019330
  3.4505786197539581 13.7206521286548160  6.6858384791168790
  5.0018491849586946 12.1494886331945597  8.5154031576508036
 15.5318858759041412  5.2315769597233333  1.4257370559054936
 10.0552703619065493 13.9627271385122746 13.3292267296548061
  6.8386195678557460  7.0152820404524814 10.1820515930480795
  5.1801358057509539  1.7916257930718216  8.4560902193881144
  5.0645666020853133 15.3441556644507102  8.5633982780536915
  8.6362113266348519 15.3369956594183208 12.1351659159201777
 11.8571869321614098 15.5382977990575686 15.3924236412736377
 17.1862306660646453 10.4703495479747239  6.7787119827867821
  9.9807168973151263 13.4311315275540366 17.3479367944420382
  6.8207685091231429 10.1690928473280060 13.6719301625909839
  3.4253621137017851  6.9133554900235312 10.1261083196503705
  1.7473128320824325  4.9075975192256047  8.6687936999569146
 17.0682736527821817 17.0380702115245839  6.7596355023775203
 10.4392294185845547  6.7293349846285615 17.0827272304924378
  5.3632614025584049  1.7013026390276063 12.1080130697651178
  8.3386877803017629  1.4819793422847032 15.1641644062706487
  7.0322346479147049 17.2308941631360248 13.8321179088105080
  5.1080319842054660  5.2104499297206566 15.3393458081628928
  5.0400141843182400  1.4941678595793375 15.4226212500981692
  6.8399768478134098 17.0690639117589846 17.1454121759285201
  1.8601216840717383 11.9295286862456571 15.3455861345636890
 15.5413788765571539  8.7628073099270267 12.0171189021022968
 17.0170688373090400  3.3095953358538694 13.7149891233028178
  3.3343947813635118  3.3165682611901830 17.1469479806339820
 16.9079913581850008 17.0939695713367605 13.5726126469146848
 17.0637544003265056 17.1631487525418116 17.0077100280484501
 13.6085087214363387  6.7839541694315271  3.2092321478237222
 13.4617121779549080  3.4163825060379192  3.3196533316353944
 11.9586455109141365 12.0040286041825457  5.1622527953135267
  8.6066920320241671  8.4845908647522457  1.6244039035444302
 13.5695758735774845  3.2890336653928332  6.7444488362262014
 13.4570490551977606 17.0417476603545417  6.8892326399872399
  8.6319020192757279 11.9676245897410940  5.0065005205179540
  5.1553265039485554  8.6060926012052921  1.7249677400106682
 13.6601520080408729 10.2450309362642713 10.2227354876232965
  6.8767972519571625  3.4954043787414819  3.3004274518969678
 13.6185772194049868  3.3382439539285502 10.2082825078531325
  6.8176770832829563 13.7317618321239294  6.7962221295787835
  8.7577304042908679 12.0214743642028381  8.4855331879345552
  3.3877420515066405  6.8101009171908498  3.3080488935935617
  5.1658606685945854  5.1352473153877591  5.1916129250203911
 13.6030961153780527 10.3107829767209260 13.6591855745365915
 10.2478536936533580  6.8464711793940394 10.2433440703047864
  5.0808821493413099  1.7556472185125831  5.1037520941773966
  8.6023417861042546  1.7216370196448669  8.4909738227057296
  6.7518604862305356 17.0030854912817411  6.8999739344798376
  6.9415600738162579 13.7606924509617983 10.2606312590274893
  1.6693046811374634  8.7046451727520484  5.0956460851519694
  3.3585113980839991  6.8777356966187719  6.9831772663337661
  1.7968101045205362  4.9823302103296578  5.0948362468993453
 17.1310776612381979  3.3641820717428312  3.2433647999123494
 13.6377171275827394 13.6924816433934957 17.0519798273484042
  5.2794120739244184  5.1258955634957548  8.5548212917012822
 13.6001314015200183 10.3321385292253698 17.0681907782293649
  8.3798514707889016  5.1057297711052225 11.8540119188173829
 13.5777232011500679  3.5003659467603301 17.1244819529467023
 17.0982841576208351 13.6985274635994916  6.7447757999102418
 15.4353586126909494  8.5502041622391243  5.0649721420814746
 15.3074306336957324  5.1757432012662701  5.1095695301037267
  8.4898342516333880 11.9644323154602237 15.1822711359333926
  5.1152883742171991  8.5433963722683828 11.9445820571858370
 17.0829022512800393  3.3920670064074034  6.8540770732795648
  1.6426065251427084  1.5967196745182806  8.5259507876661100
  8.5020741474585932  5.1962081198263723 15.3967323353530343
  1.7188983062629544 15.3750983352750570  8.5343892713722287
  5.1631390008497684 15.4480288042033589 12.0764163718754851
 15.4274405159028198  8.5935016209129742  8.4457375966818571
 17.1067975696383705  6.8230256095370159 10.1725936463614826
  6.8220639888496519 10.3642958649917496 17.0690260580280864
  1.7277785604043323  5.0627981148643730 11.9189690519641616
  3.5437025234614654  3.3680775600873254 13.7523754241150051
  1.6008403978768388  1.6674791652435215 12.0163045536371094
  6.7063775404658639  3.3654117561655021 16.9382848802418309
 17.0543382904869638 13.6815134480481984 13.6562843076391420
 17.0836645932237907  6.9401747741154507 13.6670850444913032
  1.7029014044132051 15.4756066213310479 15.3374844308733689


</p>
</details>

**Comment by janosh** [comment]
I already updated your comment above.

**Comment by Asif-Iqbal-Bhatti** [comment]
[POSCAR.tar.gz](https://github.com/materialsvirtuallab/matgl/files/11692083/POSCAR.tar.gz)

**Comment by kenko911** [comment]
Hi! I tried to reproduce the error you mentioned and the relaxation was completed at epoch 76. The following output is what I got. Could you please make sure you are using the latest release version (i.e. 0.0.5) and try it again? please let me know if the problem still exists. Thanks!
<Details >
       Step     Time          Energy         fmax
*Force-consistent energies used in optimization.
LBFGS:    0 11:15:24    -2084.408691*    3282.9336
LBFGS:    1 11:15:24    -2339.378906*    1081.1207
LBFGS:    2 11:15:25    -2405.731201*     394.9171
LBFGS:    3 11:15:25    -2332.836426*    1039.4661
LBFGS:    4 11:15:25    -2363.354980*     606.7337
LBFGS:    5 11:15:26    -2377.228027*     663.6783
LBFGS:    6 11:15:26    -2380.202637*     603.7922
LBFGS:    7 11:15:26    -2386.065430*     397.5022
LBFGS:    8 11:15:27    -2360.362549*     937.5939
LBFGS:    9 11:15:27    -2338.227539*     923.2596
LBFGS:   10 11:15:27    -2394.600586*     356.3901
LBFGS:   11 11:15:28    -2405.003418*     151.5613
LBFGS:   12 11:15:28    -2406.576660*      36.8205
LBFGS:   13 11:15:28    -2407.720459*      81.8150
LBFGS:   14 11:15:28    -2406.705078*     139.7415
LBFGS:   15 11:15:29    -2410.218018*     405.8143
LBFGS:   16 11:15:29    -2410.765869*     110.4069
LBFGS:   17 11:15:30    -2416.180176*     132.4474
LBFGS:   18 11:15:30    -2410.615479*     361.4041
LBFGS:   19 11:15:30    -2418.796143*      63.3267
LBFGS:   20 11:15:31    -2419.407227*      34.3848
LBFGS:   21 11:15:31    -2420.136475*      17.8003
LBFGS:   22 11:15:32    -2420.397217*      25.7612
LBFGS:   23 11:15:32    -2420.711426*      28.9631
LBFGS:   24 11:15:32    -2420.857666*      19.3138
LBFGS:   25 11:15:33    -2420.989990*      14.0735
LBFGS:   26 11:15:33    -2421.072266*      14.5305
LBFGS:   27 11:15:33    -2421.140869*      15.0402
LBFGS:   28 11:15:34    -2421.193115*      10.7200
LBFGS:   29 11:15:34    -2421.232910*       9.0228
LBFGS:   30 11:15:35    -2421.265625*      10.9209
LBFGS:   31 11:15:35    -2421.289795*       7.4987
LBFGS:   32 11:15:35    -2421.303955*       4.8137
LBFGS:   33 11:15:36    -2421.313965*       3.3847
LBFGS:   34 11:15:36    -2421.323486*       5.6923
LBFGS:   35 11:15:37    -2421.334717*       5.8428
LBFGS:   36 11:15:37    -2421.343018*       4.1414
LBFGS:   37 11:15:37    -2421.347412*       1.4366
LBFGS:   38 11:15:38    -2421.350342*       2.0008
LBFGS:   39 11:15:38    -2421.354248*       2.9742
LBFGS:   40 11:15:39    -2421.359375*       3.1535
LBFGS:   41 11:15:39    -2421.362549*       1.9578
LBFGS:   42 11:15:39    -2421.364502*       1.0970
LBFGS:   43 11:15:40    -2421.365967*       1.1839
LBFGS:   44 11:15:40    -2421.367676*       1.5338
LBFGS:   45 11:15:40    -2421.369629*       1.5234
LBFGS:   46 11:15:41    -2421.371094*       1.2913
LBFGS:   47 11:15:41    -2421.372314*       0.9916
LBFGS:   48 11:15:42    -2421.372803*       0.6059
LBFGS:   49 11:15:42    -2421.373291*       0.7206
LBFGS:   50 11:15:42    -2421.374512*       1.4263
LBFGS:   51 11:15:43    -2421.375488*       1.8707
LBFGS:   52 11:15:43    -2421.375977*       1.2355
LBFGS:   53 11:15:43    -2421.376465*       0.2866
LBFGS:   54 11:15:44    -2421.376709*       0.6519
LBFGS:   55 11:15:44    -2421.377197*       1.2919
LBFGS:   56 11:15:45    -2421.378174*       1.5566
LBFGS:   57 11:15:45    -2421.378418*       0.9302
LBFGS:   58 11:15:45    -2421.378662*       0.1567
LBFGS:   59 11:15:46    -2421.378418*       0.7131
LBFGS:   60 11:15:46    -2421.378906*       0.9967
LBFGS:   61 11:15:46    -2421.379150*       0.8564
LBFGS:   62 11:15:47    -2421.379150*       0.3210
LBFGS:   63 11:15:47    -2421.379150*       0.1242
LBFGS:   64 11:15:48    -2421.379395*       0.4205
LBFGS:   65 11:15:48    -2421.379395*       0.7692
LBFGS:   66 11:15:48    -2421.379639*       0.5267
LBFGS:   67 11:15:49    -2421.379883*       0.1576
LBFGS:   68 11:15:49    -2421.379639*       0.2968
LBFGS:   69 11:15:49    -2421.379639*       0.2964
LBFGS:   70 11:15:50    -2421.379639*       0.2465
LBFGS:   71 11:15:50    -2421.379639*       0.6071
LBFGS:   72 11:15:51    -2421.379883*       0.1803
LBFGS:   73 11:15:51    -2421.379639*       0.0706
LBFGS:   74 11:15:51    -2421.379883*       0.2122
LBFGS:   75 11:15:52    -2421.379639*       0.0941
LBFGS:   76 11:15:52    -2421.379883*       0.0419

**Comment by Asif-Iqbal-Bhatti** [comment]
Thanks after updating the code it is converging. I used wrongly stress_weight = 1.0 that is why the forces were higher.
