### ISSUE TITLE
Example for fine-tuning m3gnet

### ISSUE THREAD

**Issue by jic198** [materialsvirtuallab/matgl#71]
Hello. I would like to train a new model with the pre-trained m3gnet and my own AIMD trajectories data. Could you share an example of how to do it? Thank you so much!

**Comment by usccolumbia** [comment]
i have the same question... any idea?

**Comment by SmallBearC** [comment]
I have the same question, so may this feature be released in advance? I feel that the training of the previous version of TensorFlow's m3GNET is already very convenient. And this has never been directly usable. Because our dataset is different

**Comment by shyuep** [comment]
There is already a training example in the https://github.com/materialsvirtuallab/matgl/blob/main/tests/utils/test_training.py . All that needs to be done is to replace the relevant model with the loaded pre-trained model you want to use. The rest of the code should be relatively self-explanatory.

We will provide an actual script that was used for training soon.

**Comment by shyuep** [comment]
A new notebook has been added. Pls refer to the tutorials page on matgl.ai.

**Comment by SmallBearC** [comment]
I am delighted to have access to the newly released script, which now enables me to carry out the m3GNET training on my CPU device. Nevertheless, upon attempting to use the GPU (I have tested both multi-card and single-card configurations using 8 1080ti cards), an error occurred as follows:


dgl._ffi.base.DGLError: Cannot assign edge feature "bond_vec" on device cpu to a graph on device cuda:0. Cal.


I have enclosed the complete error message as an attachment for your reference. I eagerly await the resolution of this matter.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "materialsvirtuallab/matgl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月20日(星期二) 晚上10:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [materialsvirtuallab/matgl] Example for fine-tuning m3gnet (Issue #71)





 
There is already a training example in the https://github.com/materialsvirtuallab/matgl/blob/main/tests/utils/test_training.py . All that needs to be done is to replace the relevant model with the loaded pre-trained model you want to use. The rest of the code should be relatively self-explanatory.
 
We will provide an actual script that was used for training soon.

**Comment by shyuep** [comment]
You need to set your default torch device to cuda. Pls Google for the instructions.

**Comment by bawanglong-2** [comment]
> I am delighted to have access to the newly released script, which now enables me to carry out the m3GNET training on my CPU device. Nevertheless, upon attempting to use the GPU (I have tested both multi-card and single-card configurations using 8 1080ti cards), an error occurred as follows:
> 
> 
> dgl._ffi.base.DGLError: Cannot assign edge feature "bond_vec" on device cpu to a graph on device cuda:0. Cal.
> 
> 
> I have enclosed the complete error message as an attachment for your reference. I eagerly await the resolution of this matter.
> 我很高兴能够使用新发布的脚本，它现在使我能够在 CPU 设备上进行 m3GNET 训练。然而，在尝试使用 GPU（我测试了多卡和单卡配置，使用了 8 块 1080ti 显卡）时，发生了如下错误：
> 
> 
> dgl._ffi.base.DGLError: 不能在设备 cpu 上分配边特征 "bond_vec" 到设备 cuda:0 的图上。Cal。
> 
> 
> 我已将完整的错误信息作为附件附上供您参考。我热切期待此事的解决。
> […](#)



> I have the same question, so may this feature be released in advance? I feel that the training of the previous version of TensorFlow's m3GNET is already very convenient. And this has never been directly usable. Because our dataset is different我也有同样的问题，所以这个功能能提前发布吗？我觉得之前版本的 TensorFlow 的 m3GNET 训练已经非常方便了。而这个一直不能直接使用。因为我们的数据集不同

Hello, I've been trying to learn how to use the fine-tuning process of m3gnet recently. My python proficiency is relatively low, and I can't quite understand the content explained by the official. I also can't find any related video tutorials. Currently, I have two bottlenecks: how to convert the output data of many structures of VASP to M3GNET and how to make it only perform fine-tuning functions. I'd like to ask if you have any relevant insights or code to share. I'm very sorry to disturb you.
