### ISSUE TITLE
When running trian_mp_eform.py, I was prompted for unexpected real parameters.

### ISSUE THREAD

**Issue by Taylor112233** [materialsvirtuallab/matgl#81]
Thanks for providing such an wonderful work.
I'm trying to run "trian_mp_eform.py", but I'm getting an error：
      "trainer. train(
      TypeError: train() got an unexpected keyword argument 'n_epochs'”

How should I modify it to avoid this error.

**Comment by rashigeek** [comment]
I am also experiencing this issue #82. Were you able to resolve it?

**Comment by Taylor112233** [comment]
> I am also experiencing this issue #82. Were you able to resolve it?

I haven't solved this problem yet.
But I think the part that trains the network is missing in this code.
