### ISSUE TITLE
Error when trying to train MEGNet model on MP-2018.6.1

### ISSUE THREAD

**Issue by rashigeek** [materialsvirtuallab/matgl#82]
I am trying to run the script here:
https://github.com/materialsvirtuallab/matgl/blob/main/examples/training/MEGNet/MP-2018.6.1-Eform/train_mp_eform.py

And I am getting the following error. 

> Traceback (most recent call last):
>   File "/home/trial/matgl-try/matgl/examples/training/MEGNet/MP-2018.6.1-Eform/train_mp_eform.py", line 130, in <module>
>     trainer.train(
> TypeError: train() got an unexpected keyword argument 'n_epochs'

Here is how to reproduce this issue assuming you have Conda or Miniconda installed:

1. Create a new directory:
`mkdir matgel-try`

2. Create a conda environment with Python 3.9:
`conda create -n matgl-trial python=3.9`

3. Activate the Conda environment: 
`conda activate matgl-trial`

4. Clone the repo:
`git clone https://github.com/materialsvirtuallab/matgl.git`

5. cd into the repo:
`cd matgl/`

6. install the package using the editable option:
`pip install -e .`
 
7. Run the script:
`python examples/training/MEGNet/MP-2018.6.1-Eform/train_mp_eform.py`

In fact, running the help function in the class method through the command `help(trainer.train)` gives the following:

> Help on method train in module torch.nn.modules.module:
> 
> train(mode: bool = True) -> ~T method of matgl.utils.training.ModelTrainer instance
>     Sets the module in training mode.
>     
>     This has any effect only on certain modules. See documentations of
>     particular modules for details of their behaviors in training/evaluation
>     mode, if they are affected, e.g. :class:`Dropout`, :class:`BatchNorm`,
>     etc.
>     
>     Args:
>         mode (bool): whether to set training mode (``True``) or evaluation
>                      mode (``False``). Default: ``True``.
>     
>     Returns:
>         Module: self
>  

 
The Arguments for the method do not seem to match the provided arguments. I think this error is due to updates that rolled out this month for both torch and pytorch-lightening but I am not sure how to fix it. 

- Ahmed

**Comment by rashigeek** [comment]
This issue seems to be a duplicate of #81 . The title was not clear so I did not realize it was the same issue.

**Comment by shyuep** [comment]
A solution will be posted soon.
